In [4]:
%cd /home/vivek/Python-ELM
import cPickle
import pandas as pd
import numpy as np
from elm import ELMClassifier
from sklearn import linear_model

/home/vivek/Python-ELM


In [6]:
data= pd.read_pickle('/home/vivek/Documents/Data_Science/Data_Sets/mnist.pkl')


((array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
  array([5, 0, 4, ..., 8, 4, 8])),
 (array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
  array([3, 8, 6, ..., 5, 6, 8])),
 (array([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         ..., 
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.],
         [ 0.,  0.,  0., ...,  0.,  0.,  0.]], dtype=float32),
  arra

In [11]:
train_x, train_y = data[0][0], np.array(data[0][1]).reshape(len(data[0][1]), 1)
val_x, val_y = data[1][0], np.array(data[1][1]).reshape(len(data[1][1]), 1)
test_x, test_y = data[2][0], np.array(data[2][1]).reshape(len(data[2][1]), 1)

In [9]:
cls = ELMClassifier(n_hidden=7000,
                        alpha=0.93,
                        activation_func='multiquadric',
                        regressor=linear_model.Ridge(),
                        random_state=21398023)

In [13]:
cls.fit(train_x, train_y)

ELMClassifier(activation_args=None, activation_func='multiquadric',
       alpha=0.93,
       binarizer=LabelBinarizer(neg_label=-1, pos_label=1, sparse_output=False),
       n_hidden=7000, random_state=21398023, rbf_width=1.0,
       regressor=Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
   normalize=False, random_state=None, solver='auto', tol=0.001),
       user_components=None)

In [14]:
cls.score(test_x,test_y)

0.97019999999999995

In [15]:
cls.score(val_x, val_y)

0.97330000000000005